import '@/styles/globals.css';

import clsx from 'clsx';
import type { Metadata } from 'next';

import { ThemeProvider } from '@/components/ui/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { axiforma } from '@/configs/fonts.configs';
import StoreProvider from '@/contexts/StoreProvider';

export const metadata: Metadata = {
  title:
    'Blog.dev | Where you can sharing, stay up-to-date and grow their careers',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(axiforma.variable, 'font-axiforma')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          storageKey="dev-blog-theme"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            {children}
            <Toaster />
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
