import '@/styles/globals.css'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { Ubuntu_Sans } from 'next/font/google'

import DesktopMenu from '@/components/layouts/DesktopMenu'
import Header from '@/components/layouts/Header'
import MobileMenu from '@/components/layouts/MobileMenu'
import { ThemeProvider } from '@/components/ui/theme-provider'

export const metadata: Metadata = {
  title:
    'Blog.dev | Where you can sharing, stay up-to-date and grow their careers',
  description: 'Generated by create next app',
}

const ubuntuSans = Ubuntu_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-ubuntu-sans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx('flex flex-col font-ubuntu-sans', ubuntuSans.variable)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          storageKey="dev-blog-theme"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="relative flex flex-1">
            <DesktopMenu />
            <MobileMenu />
            <div
              className={`
                mt-6 flex-1 px-2

                lg:ml-60 lg:px-6

                md:ml-16 md:px-4
              `}
            >
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
